### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by oretselo** [RecoveryOutlet/Spos#2]
The Home Quick Play option is working but the greeting for me is wrong.

Also can you add the Sleep Timer button/option in Now playing UI?
Thank you so much. 
![08EDF52F-6041-4525-887B-820371E17668](https://user-images.githubusercontent.com/21124594/63715025-8a634080-c875-11e9-82a4-4815ec453774.jpeg)

**Comment by RecoveryOutlet** [comment]
Sleep timer will not be added to the ui and also the good evening spotify need to fix that not me
